<a href="https://colab.research.google.com/github/yashraj02/Tensorflow/blob/master/Tensorflow_Low_Level_APIs%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Explore Tensorflow Low level operations.**   
This code has required version dependencies.  
Kindly run the pip commands mentioned at the bottom of the pasge for version interruptions 

In [33]:
import tensorflow as tf
print(tf.__version__)
hello = tf.constant("Hello")
world = tf.constant("World")
print(hello)
with tf.Session() as sess:
  result = sess.run(hello)
print(result)

1.13.1
Tensor("Const_10:0", shape=(), dtype=string)
b'Hello'


In [32]:
import tensorflow as tf
sess = tf.InteractiveSession()
my_tensor = tf.random_uniform((4,4),0,1)
my_var = tf.Variable(my_tensor)
# sess.run(my_var)
init = tf.global_variables_initializer()
sess.run(init)
sess.run(my_var)

In [ ]:
ph = tf.placeholder(tf.float32, shape=(None,5))


TF GRAPH

In [ ]:
import numpy as np
import tensorflow as tf
tf.set_random_seed(101)
randomA = np.random.uniform(0,100,(5,5))
randomA

array([[82.87681837, 98.16531445, 85.12881022, 72.67286419, 59.81111552],
       [44.56124753, 23.68516204, 84.11915722, 32.04421209, 38.15938748],
       [69.99652914, 53.86294004, 84.52563407,  8.53828287, 61.17231677],
       [25.03770966, 22.97964399,  4.52312408, 23.26226351, 36.54418297],
       [62.55222649, 33.0530819 ,  0.17920249, 47.20841451, 74.21472355]])

In [ ]:
randomB = np.random.uniform(0,100,(5,1))
randomB

array([[22.64085176],
       [96.43023067],
       [67.59181796],
       [61.18533988],
       [13.2868955 ]])

In [ ]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [ ]:
add_op = a + b
mul_op = a*b

In [ ]:
with tf.Session() as sess:
  add_result = sess.run(add_op, feed_dict={a:randomA, b:randomB})
  print(add_result)
  print('*'*100)
  multiply_result = sess.run(mul_op, feed_dict={a:randomA, b:randomB})
  print(multiply_result)
  print('*'*100)

[[105.51767  120.80617  107.76966   95.31372   82.451965]
 [140.99149  120.11539  180.54938  128.47444  134.58961 ]
 [137.58835  121.45476  152.11746   76.130104 128.76413 ]
 [ 86.22305   84.164986  65.708466  84.4476    97.72952 ]
 [ 75.83913   46.339977  13.466098  60.49531   87.50162 ]]
****************************************************************************************************
[[1.8764017e+03 2.2225464e+03 1.9273887e+03 1.6453756e+03 1.3541746e+03]
 [4.2970513e+03 2.2839656e+03 8.1116294e+03 3.0900308e+03 3.6797183e+03]
 [4.7311929e+03 3.6406943e+03 5.7132417e+03 5.7711804e+02 4.1347480e+03]
 [1.5319408e+03 1.4060175e+03 2.7674890e+02 1.4233096e+03 2.2359683e+03]
 [8.3112494e+02 4.3917285e+02 2.3810446e+00 6.2725330e+02 9.8608325e+02]]
****************************************************************************************************


Example Neural Network

In [11]:
import numpy as np
import tensorflow as tf
nfeatures = 10
neurons = 3
x = tf.placeholder(tf.float32,(None,nfeatures))
W = tf.Variable(tf.random_normal([nfeatures,neurons]))
b = tf.Variable(tf.ones([neurons]))
xW = tf.matmul(x,W)
z = tf.add(xW,b)
a = tf.sigmoid(z)
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  layer_out = sess.run(a, feed_dict={x:np.random.random([1,nfeatures])})
print("Predictions : ",layer_out)

Predictions :  [[0.63849425 0.33210474 0.3174785 ]]


In [ ]:
!pip install _ipyw_jlab_nb_ext_conf==0.1.0
!pip install absl-py==0.9.0
!pip install alabaster==0.7.12
!pip install anaconda==2020.02
!pip install anaconda-client==1.7.2
!pip install anaconda-navigator==1.9.12
!pip install anaconda-project==0.8.4
!pip install argh==0.26.2
!pip install asn1crypto==1.3.0
!pip install astor==0.8.1
!pip install astroid==2.3.3
!pip install astropy==4.0
!pip install atomicwrites==1.3.0
!pip install attrs==19.3.0
!pip install autopep8==1.4.4
!pip install babel==2.8.0
!pip install backcall==0.1.0
!pip install backports==1.0
!pip install backports.functools_lru_cache==1.6.1
!pip install backports.shutil_get_terminal_size==1.0.0
!pip install backports.tempfile==1.0
!pip install backports.weakref==1.0.post1
!pip install bcrypt==3.1.7
!pip install beautifulsoup4==4.8.2
!pip install bitarray==1.2.1
!pip install bkcharts==0.2
!pip install blas==1.0
!pip install bleach==3.1.0
!pip install blosc==1.16.3
!pip install bokeh==1.4.0
!pip install boto==2.49.0
!pip install bottleneck==1.3.2
!pip install bzip2==1.0.8
!pip install ca-certificates==2020.1.1
!pip install certifi==2019.11.28
!pip install cffi==1.14.0
!pip install chardet==3.0.4
!pip install click==7.0
!pip install cloudpickle==1.3.0
!pip install clyent==1.2.2
!pip install colorama==0.4.3
!pip install comtypes==1.1.7
!pip install conda==4.8.3
!pip install conda-build==3.18.11
!pip install conda-env==2.6.0
!pip install conda-package-handling==1.6.0
!pip install conda-verify==3.4.2
!pip install console_shortcut==0.1.1
!pip install contextlib2==0.6.0.post1
!pip install cryptography==2.8
!pip install curl==7.68.0
!pip install cycler==0.10.0
!pip install cython==0.29.15
!pip install cytoolz==0.10.1
!pip install dask==2.11.0
!pip install dask-core==2.11.0
!pip install decorator==4.4.1
!pip install defusedxml==0.6.0
!pip install diff-match-patch==20181111
!pip install distributed==2.11.0
!pip install docutils==0.16
!pip install entrypoints==0.3
!pip install et_xmlfile==1.0.1
!pip install fastcache==1.1.0
!pip install filelock==3.0.12
!pip install flake8==3.7.9
!pip install flask==1.1.1
!pip install freetype==2.9.1
!pip install fsspec==0.6.2
!pip install future==0.18.2
!pip install gast==0.3.3
!pip install get_terminal_size==1.0.0
!pip install gevent==1.4.0
!pip install glob2==0.7
!pip install greenlet==0.4.15
!pip install grpcio==1.23.0
!pip install h5py==2.10.0
!pip install hdf5==1.10.4
!pip install heapdict==1.0.1
!pip install html5lib==1.0.1
!pip install hypothesis==5.5.4
!pip install icc_rt==2019.0.0
!pip install icu==58.2
!pip install idna==2.8
!pip install imageio==2.6.1
!pip install imagesize==1.2.0
!pip install importlib-metadata==1.7.0
!pip install importlib_metadata==1.5.0
!pip install intel-openmp==2020.0
!pip install intervaltree==3.0.2
!pip install ipykernel==5.1.4
!pip install ipython==7.12.0
!pip install ipython_genutils==0.2.0
!pip install ipywidgets==7.5.1
!pip install isort==4.3.21
!pip install itsdangerous==1.1.0
!pip install jdcal==1.4.1
!pip install jedi==0.14.1
!pip install jinja2==2.11.1
!pip install joblib==0.14.1
!pip install jpeg==9b
!pip install json5==0.9.1
!pip install jsonschema==3.2.0
!pip install jupyter==1.0.0
!pip install jupyter_client==5.3.4
!pip install jupyter_console==6.1.0
!pip install jupyter_core==4.6.1
!pip install jupyterlab==1.2.6
!pip install jupyterlab_server==1.0.6
!pip install keras==2.3.1
!pip install keras-applications==1.0.8
!pip install keras-preprocessing==1.1.0
!pip install keyring==21.1.0
!pip install kiwisolver==1.1.0
!pip install krb5==1.17.1
!pip install lazy-object-proxy==1.4.3
!pip install libarchive==3.3.3
!pip install libcurl==7.68.0
!pip install libgpuarray==0.7.6
!pip install libiconv==1.15
!pip install liblief==0.9.0
!pip install libpng==1.6.37
!pip install libprotobuf==3.12.3
!pip install libsodium==1.0.16
!pip install libspatialindex==1.9.3
!pip install libssh2==1.8.2
!pip install libtiff==4.1.0
!pip install libxml2==2.9.9
!pip install libxslt==1.1.33
!pip install llvmlite==0.31.0
!pip install locket==0.2.0
!pip install lxml==4.5.0
!pip install lz4-c==1.8.1.2
!pip install lzo==2.10
!pip install m2w64-gcc-libgfortran==5.3.0
!pip install m2w64-gcc-libs==5.3.0
!pip install m2w64-gcc-libs-core==5.3.0
!pip install m2w64-gmp==6.1.0
!pip install m2w64-libwinpthread-git==5.0.0.4634.697f757
!pip install mako==1.1.0
!pip install markdown==3.2.2
!pip install markupsafe==1.1.1
!pip install matplotlib==3.1.3
!pip install matplotlib-base==3.1.3
!pip install mccabe==0.6.1
!pip install menuinst==1.4.16
!pip install mistune==0.8.4
!pip install mkl==2020.0
!pip install mkl-service==2.3.0
!pip install mkl_fft==1.0.15
!pip install mkl_random==1.1.0
!pip install mock==4.0.1
!pip install more-itertools==8.2.0
!pip install mpmath==1.1.0
!pip install msgpack-python==0.6.1
!pip install msys2-conda-epoch==20160418
!pip install multipledispatch==0.6.0
!pip install navigator-updater==0.2.1
!pip install nbconvert==5.6.1
!pip install nbformat==5.0.4
!pip install networkx==2.4
!pip install nltk==3.4.5
!pip install nose==1.3.7
!pip install notebook==6.0.3
!pip install numba==0.48.0
!pip install numexpr==2.7.1
!pip install numpy==1.18.1
!pip install numpy-base==1.18.1
!pip install numpydoc==0.9.2
!pip install olefile==0.46
!pip install openpyxl==3.0.3
!pip install openssl==1.1.1d
!pip install packaging==20.1
!pip install pandas==1.0.1
!pip install pandoc==2.2.3.2
!pip install pandocfilters==1.4.2
!pip install paramiko==2.7.1
!pip install parso==0.5.2
!pip install partd==1.1.0
!pip install path==13.1.0
!pip install path.py==12.4.0
!pip install pathlib2==2.3.5
!pip install pathtools==0.1.2
!pip install patsy==0.5.1
!pip install pep8==1.7.1
!pip install pexpect==4.8.0
!pip install pickleshare==0.7.5
!pip install pillow==7.0.0
!pip install !pip==20.0.2
!pip install pkginfo==1.5.0.1
!pip install pluggy==0.13.1
!pip install ply==3.11
!pip install powershell_shortcut==0.0.1
!pip install prometheus_client==0.7.1
!pip install prompt_toolkit==3.0.3
!pip install protobuf==3.12.3
!pip install psutil==5.6.7
!pip install py==1.8.1
!pip install py-lief==0.9.0
!pip install pycodestyle==2.5.0
!pip install pycosat==0.6.3
!pip install pycparser==2.19
!pip install pycrypto==2.6.1
!pip install pycurl==7.43.0.5
!pip install pydocstyle==4.0.1
!pip install pyflakes==2.1.1
!pip install pygments==2.5.2
!pip install pygpu==0.7.6
!pip install pylint==2.4.4
!pip install pynacl==1.3.0
!pip install pyodbc==4.0.30
!pip install pyopenssl==19.1.0
!pip install pyparsing==2.4.6
!pip install pyqt==5.9.2
!pip install pyreadline==2.1
!pip install pyrsistent==0.15.7
!pip install pysocks==1.7.1
!pip install pytables==3.6.1
!pip install pytest==5.3.5
!pip install pytest-arraydiff==0.3
!pip install pytest-astropy==0.8.0
!pip install pytest-astropy-header==0.1.2
!pip install pytest-doctestplus==0.5.0
!pip install pytest-openfiles==0.4.0
!pip install pytest-remotedata==0.3.2
!pip install python==3.7.6
!pip install python-dateutil==2.8.1
!pip install python-jsonrpc-server==0.3.4
!pip install python-language-server==0.31.7
!pip install python-libarchive-c==2.8
!pip install python_abi==3.7
!pip install pytz==2019.3
!pip install pywavelets==1.1.1
!pip install pywin32==227
!pip install pywin32-ctypes==0.2.0
!pip install pywinpty==0.5.7
!pip install pyyaml==5.3
!pip install pyzmq==18.1.1
!pip install qdarkstyle==2.8
!pip install qt==5.9.7
!pip install qtawesome==0.6.1
!pip install qtconsole==4.6.0
!pip install qtpy==1.9.0
!pip install requests==2.22.0
!pip install rope==0.16.0
!pip install rtree==0.9.3
!pip install ruamel_yaml==0.15.87
!pip install scikit-image==0.16.2
!pip install scikit-learn==0.22.1
!pip install scipy==1.4.1
!pip install seaborn==0.10.0
!pip install send2trash==1.5.0
!pip install setuptools==45.2.0
!pip install simplegeneric==0.8.1
!pip install singledispatch==3.4.0.3
!pip install sip==4.19.8
!pip install six==1.14.0
!pip install snappy==1.1.7
!pip install snowballstemmer==2.0.0
!pip install sortedcollections==1.1.2
!pip install sortedcontainers==2.1.0
!pip install soupsieve==1.9.5
!pip install sphinx==2.4.0
!pip install sphinxcontrib==1.0
!pip install sphinxcontrib-applehelp==1.0.1
!pip install sphinxcontrib-devhelp==1.0.1
!pip install sphinxcontrib-htmlhelp==1.0.2
!pip install sphinxcontrib-jsmath==1.0.1
!pip install sphinxcontrib-qthelp==1.0.2
!pip install sphinxcontrib-serializinghtml==1.1.3
!pip install sphinxcontrib-websupport==1.2.0
!pip install spyder==4.0.1
!pip install spyder-kernels==1.8.1
!pip install sqlalchemy==1.3.13
!pip install sqlite==3.31.1
!pip install statsmodels==0.11.0
!pip install sympy==1.5.1
!pip install tbb==2020.0
!pip install tblib==1.6.0
!pip install tensorboard==1.13.1
!pip install tensorflow==1.13.1
!pip install tensorflow-estimator==1.13.0
!pip install termcolor==1.1.0
!pip install terminado==0.8.3
!pip install testpath==0.4.4
!pip install theano==1.0.4
!pip install tk==8.6.8
!pip install toolz==0.10.0
!pip install tornado==6.0.3
!pip install tqdm==4.42.1
!pip install traitlets==4.3.3
!pip install ujson==1.35
!pip install unicodecsv==0.14.1
!pip install urllib3==1.25.8
!pip install vc==14.1
!pip install vs2015_runtime==14.16.27012
!pip install vs2017_win-64==19.16.27038
!pip install vswhere==2.7.1
!pip install watchdog==0.10.2
!pip install wcwidth==0.1.8
!pip install webencodings==0.5.1
!pip install werkzeug==1.0.0
!pip install wheel==0.34.2
!pip install widgetsnbextension==3.5.1
!pip install win_inet_pton==1.1.0
!pip install win_unicode_console==0.5
!pip install wincertstore==0.2
!pip install winpty==0.4.3
!pip install wrapt==1.11.2
!pip install xlrd==1.2.0
!pip install xlsxwriter==1.2.7
!pip install xlwings==0.17.1
!pip install xlwt==1.3.0
!pip install xmltodict==0.12.0
!pip install xz==5.2.4
!pip install yaml==0.1.7
!pip install yapf==0.28.0
!pip install zeromq==4.3.1
!pip install zict==1.0.0
!pip install zipp==2.2.0
!pip install zlib==1.2.11
!pip install zstd==1.3.7
!pip install netron====4.3.8